### ISSUE TITLE
Create page on why apache stopped running after a few days

### ISSUE THREAD

**Issue by timjrobinson** [c9/docs.c9.io#139]
Explain to free users that their workspace is archived after a few days of inactivity and this causes processes like apache to stop running.

**Comment by basdewachter** [comment]
And actually explain that we are not a hosting provider (yet).
C9 is intended to develop and test your code, show it to a customer or so.
We do and *can* not make any guarantees or promises about how long they will run.

**Comment by basdewachter** [comment]
+1

**Comment by bradydowling** [comment]
This is included in an FAQ in the readme docs. This can be moved to another doc if that would more applicable.

**Comment by timjrobinson** [comment]
@bradydowling This can be closed, I think we need a page on workspace archiving in general though, there doesn't seem to be any docs about how often workspaces are archived and what happens when they are etc.
