### ISSUE TITLE
Redundant usage of `sudo` in some docs

### ISSUE THREAD

**Issue by murukeshm** [c9/docs.c9.io#158]
The commands in [the PostgreSQL guide](https://docs.c9.io/setting_up_postgresql.html) are using `sudo` twice, unnecessarily, IMHO:

    sudo sudo -u psql ...
Either:

- The user has been limited to `sudo -u psql *` via `sudo`, in which they might as well be granted rights to run as `psql` in `sudoers` directly,
- Or they can run pretty much anything since granting access to root's `sudo` via `sudo` is pointless as a restriction.

I think this is more of a typo or an oversight than anything else.

**Comment by murukeshm** [comment]
Ok, guess I'm not too familiar with pull requests. Sorry for the extra spam.

**Comment by bradydowling** [comment]
Wow, not sure how we got sudo in there twice but good catch! And no problem on the pull request mixup, it's a bit tricky at first.

1. Go to your own repo, the forked version of this one
2. Click on the green button in the top left
3. On the next page make sure you select this repo as the base fork and your repo as the head fork

This should do it for you but if there are further issues, feel free to reach out again and maybe a pull request doc would be a good thing to make for all Cloud9 users. The changes you made look great though, thanks again for the PR. I'll be happy to merge them in once you do that!
